### ISSUE TITLE
Release Workflow fails: ERROR: Package 'pvframework' requires a different Python: 3.10.12 not in '>=3.11'

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/pedantic-validator-framework#129]
Kurzzusammenfassung: Durch den Umzug der CI Dependencies aus den dev-requirements.txt in die pyproject.toml #128  breakt die Release/Build Pipeline Richtung PyPI, weil Teile der Build Pipeline wohl implizit auf 3.10 aufbauen und optionale Dependencies, die "eigentlich" gar nicht verwendet werden sollten im Build, wohl doch Seiteneffekte auf die Build Pipeline haben.

**Comment by FreddyFox892** [comment]
https://stackoverflow.com/questions/72851876/python-hatch-error-package-hatch-demo-requires-a-different-python-3-10-5-n
https://stackoverflow.com/questions/73116647/why-cant-i-install-a-python-package-with-the-python-requirement-3-8-3-11-i

So wie ich es verstehe schein das problem zusein dass irgendwas der dependencys 3.10 braucht
